export enum NotificationType {
    SERVICE_ACCEPTED = 'SERVICE_ACCEPTED',
    SERVICE_COMPLETED = 'SERVICE_COMPLETED',
    SERVICE_CANCELLED = 'SERVICE_CANCELLED',
    SERVICE_IN_PROGRESS = 'SERVICE_IN_PROGRESS'
}