export enum NotificationType {
    NUEVA_ACEPTACION    = 'NUEVA_ACEPTACION',
    SERVICIO_ACEPTADO   = 'SERVICIO_ACEPTADO',
    SERVICIO_EN_PROCESO = 'SERVICIO_EN_PROCESO',
    SERVICIO_COMPLETADO = 'SERVICIO_COMPLETADO',
    SERVICIO_CANCELADO  = 'SERVICIO_CANCELADO',
    SISTEMA             = 'SISTEMA',
}